builds:
  - env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w -X main.version={{.Version}}
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64
changelog:
    skip: true
archives:
  - format: binary
    name_template: "{{.Binary}}_{{.Os}}_{{.Arch}}"
