language: go

env:
  - GO111MODULE=on TEXTNOTE_DIR=/tmp

go:
  - 1.16.x

branches:
  except:
  - /^(?i:dev)\/.*$/

before_install:
  - go get github.com/modocache/gover
  - go get github.com/mattn/goveralls

script:
  - go test -v github.com/dkaslovsky/textnote/... -coverprofile=all.coverprofile
  - gover
  - goveralls -race -coverprofile gover.coverprofile -service travis-ci
